openapi: 3.0.3
info:
  title: Coffee bags
  description: |-
    A place with information about each coffee bag and their beans
  contact:
    email: coffeebags@examaple.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "202211051316"
servers:
  - url: https://coffeebags.example.org
tags:
  - name: coffee
    description: Everything about coffee
paths:
  /bags:
    get:
      tags:
        - coffee
      summary: All coffee bags
      description: Lists all known coffee bags
      operationId: all-bags
      responses:
        "200":
          $ref: "#/components/responses/CoffeeBagsResponse"
components:
  schemas:
    CoffeeBag:
      type: object
      properties:
        name:
          type: string
          description: Producer's coffee bag name
          example: Iridescent
        description:
          type: string
          description: Details about the bag
          example: |-
            Includes coffees from Ethiopia, Kenya, and Latin America. It’s a  combination of some of our best, most interesting coffees, and features notes of dark chocolate and berry. Each year, we donate $1 per pound from Iridescent to fund transformative projects in coffee-producing countries through our Seeds fund—a program that awards grants to producer-driven sustainability projects. Because good work, good cheer, and great coffee is more than just a winter theme.
        roasting:
          type: object
          properties:
            profile:
              type: string
              enum:
                - light
                - medium
                - medium-dark
                - dark
              example: Dark
              description: The roasting profile used
            date:
              type: string
              format: date
              description:  When the roasting happened
              example: 2022-11-01
            roaster:
              type: string
              format: uri
              description: Link to roster's information
              example: https://coffeebags.example.org/rosters/the-identifier
        weight:
          type: object
          properties:
            unitCode:
              type: string
              description: The unit of measurement given using the UN/CEFACT Common Code (3 characters)
              example: GRM
            unitText:
              type: string
              description: Text indicating the unit of measurement. Useful if you cannot provide a standard unit code for unitCode
              example: g
            value:
              type: number
              description: The value of the weight in the corresponding unit
              example: 340

  responses:
    CoffeeBagsResponse:
      description: |
        Collection with coffee bags or empty `{ "data": [] }`
      content:
        "application/json":
          schema:
            type: object
            properties:
              data:
                description: Standard wrapper property for collection responses
                type: array
                items:
                  $ref: "#/components/schemas/CoffeeBag"